spiriit_auth_log:
    # Email notification settings
    transports:
        sender_email: '%env(FROM_EMAIL)%'
        sender_name: 'NoReply JiraServiceDesk <%env(FROM_EMAIL)%>'

    location:
        provider: 'ipApi'

    messenger: 'messenger.default_bus'
